### ISSUE TITLE
Effect does not compile on Plasma 5.26

### ISSUE THREAD

**Issue by Kodehawa** [zzag/kwin-effects-yet-another-magic-lamp#62]
Fails with the following error on 5.26.0:

```
[ 89%] Building CXX object src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/kwin_yetanothermagiclamp_config_autogen/mocs_compilation.cpp.o
In file included from /home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/YetAnotherMagicLampEffect.cc:19:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/YetAnotherMagicLampEffect.h:25:10: fatal error: kwindeformeffect.h: No such file or directory
   25 | #include <kwindeformeffect.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:113: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/YetAnotherMagicLampEffect.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/build/src/kwin4_effect_yetanothermagiclamp_autogen/EWIEGA46WW/moc_YetAnotherMagicLampEffect.cpp:10,
                 from /home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/build/src/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp:2:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/build/src/kwin4_effect_yetanothermagiclamp_autogen/EWIEGA46WW/../../../../kwin-effects-yet-another-magic-lamp-git/src/YetAnotherMagicLampEffect.h:25:10: fatal error: kwindeformeffect.h: No such file or directory
   25 | #include <kwindeformeffect.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:85: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp.o] Error 1
In file included from /home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/plugin.cc:19:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/YetAnotherMagicLampEffect.h:25:10: fatal error: kwindeformeffect.h: No such file or directory
   25 | #include <kwindeformeffect.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:127: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/plugin.cc.o] Error 1
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In function ‘Direction realizeDirection(const KWin::EffectWindow*)’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:56:59: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
   56 |         const QRect screenRect = KWin::effects->clientArea(KWin::ScreenArea, dock);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:73:52: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
   73 |         const QRect iconRect = window->iconGeometry();
      |                                ~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:78:59: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
   78 |         const QRect screenRect = KWin::effects->clientArea(KWin::ScreenArea, screen, desktop);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:93:55: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
   93 |     const QRect screenRect = KWin::effects->clientArea(KWin::ScreenArea, window);
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In function ‘void transformQuadsLeft(const KWin::EffectWindow*, const TransformParameters&, QVector<KWin::WindowQuad>&)’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:305:48: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  305 |     const QRect iconRect = window->iconGeometry();
      |                            ~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:306:51: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  306 |     const QRect windowRect = window->frameGeometry();
      |                              ~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In function ‘void transformQuadsTop(const KWin::EffectWindow*, const TransformParameters&, QVector<KWin::WindowQuad>&)’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:348:48: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  348 |     const QRect iconRect = window->iconGeometry();
      |                            ~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:349:51: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  349 |     const QRect windowRect = window->frameGeometry();
      |                              ~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In function ‘void transformQuadsRight(const KWin::EffectWindow*, const TransformParameters&, QVector<KWin::WindowQuad>&)’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:391:48: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  391 |     const QRect iconRect = window->iconGeometry();
      |                            ~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:392:51: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  392 |     const QRect windowRect = window->frameGeometry();
      |                              ~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In function ‘void transformQuadsBottom(const KWin::EffectWindow*, const TransformParameters&, QVector<KWin::WindowQuad>&)’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:434:48: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  434 |     const QRect iconRect = window->iconGeometry();
      |                            ~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:435:51: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  435 |     const QRect windowRect = window->frameGeometry();
      |                              ~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In member function ‘QRegion Model::clipRegion() const’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:591:50: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  591 |     const QRect iconRect = m_window->iconGeometry();
      |                            ~~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:592:48: error: conversion from ‘QRectF’ to non-scalar type ‘QRect’ requested
  592 |     QRect clipRect = m_window->expandedGeometry();
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In member function ‘int Model::computeBumpDistance() const’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:632:53: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  632 |     const QRect windowRect = m_window->frameGeometry();
      |                              ~~~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:633:50: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  633 |     const QRect iconRect = m_window->iconGeometry();
      |                            ~~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc: In member function ‘qreal Model::computeShapeFactor() const’:
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:664:53: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  664 |     const QRect windowRect = m_window->frameGeometry();
      |                              ~~~~~~~~~~~~~~~~~~~~~~~^~
/home/kodehawa/.cache/yay/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/Model.cc:665:50: error: conversion from ‘QRectF’ to non-scalar type ‘const QRect’ requested
  665 |     const QRect iconRect = m_window->iconGeometry();
      |                            ~~~~~~~~~~~~~~~~~~~~~~^~
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:99: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/Model.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:360: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
