### ISSUE TITLE
Cannot install on archlinux

### ISSUE THREAD

**Issue by wojtekKrol** [zzag/kwin-effects-yet-another-magic-lamp#43]
```CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:30 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use
  Findkwineffects.cmake
Call Stack (most recent call first):
  cmake/Modules/Findkwineffects.cmake:69 (ecm_find_package_version_check)
  CMakeLists.txt:37 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The following OPTIONAL packages have been found:

 * KF5Auth (required version >= 5.83.0)
 * KF5Codecs (required version >= 5.83.0)

-- The following REQUIRED packages have been found:

 * ECM (required version >= 5.78)
 * Qt5
 * Qt5DBus (required version >= 5.15.0)
 * KF5Config (required version >= 5.83.0)
 * KF5ConfigWidgets (required version >= 5.78)
 * Qt5Core (required version >= 5.15.0)
 * KF5CoreAddons (required version >= 5.78)
 * Qt5Gui (required version >= 5.15.0)
 * KF5WindowSystem (required version >= 5.78)
 * KF5 (required version >= 5.78)
 * kwineffects
 * KWinDBusInterface
 * epoxy

-- Configuring done
-- Generating done
-- Build files have been written to: /home/wojtek/kwin-effects-yet-another-magic-lamp/build
[ 10%] Automatic MOC for target kwin4_effect_yetanothermagiclamp
AutoMoc warning
---------------
"SRC:/src/plugin.cc"
includes the moc file "plugin.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON, K_PLUGIN_CLASS_WITH_JSON, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[ 10%] Built target kwin4_effect_yetanothermagiclamp_autogen
[ 10%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp.o
In file included from /home/wojtek/kwin-effects-yet-another-magic-lamp/build/src/kwin4_effect_yetanothermagiclamp_autogen/EWIEGA46WW/moc_YetAnotherMagicLampEffect.cpp:10,
                 from /home/wojtek/kwin-effects-yet-another-magic-lamp/build/src/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp:2:
/home/wojtek/kwin-effects-yet-another-magic-lamp/build/src/kwin4_effect_yetanothermagiclamp_autogen/EWIEGA46WW/../../../../src/YetAnotherMagicLampEffect.h:25:10: fatal error: kwindeformeffect.h: Nie ma takiego pliku ani katalogu
   25 | #include <kwindeformeffect.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:85: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp.o] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:360: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/all] Błąd 2
make: *** [Makefile:146: all] Błąd 2
[  5%] Automatic MOC for target kwin4_effect_yetanothermagiclamp
AutoMoc warning
---------------
"SRC:/src/plugin.cc"
includes the moc file "plugin.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON, K_PLUGIN_CLASS_WITH_JSON, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[  5%] Built target kwin4_effect_yetanothermagiclamp_autogen
[ 10%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp.o
In file included from /home/wojtek/kwin-effects-yet-another-magic-lamp/build/src/kwin4_effect_yetanothermagiclamp_autogen/EWIEGA46WW/moc_YetAnotherMagicLampEffect.cpp:10,
                 from /home/wojtek/kwin-effects-yet-another-magic-lamp/build/src/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp:2:
/home/wojtek/kwin-effects-yet-another-magic-lamp/build/src/kwin4_effect_yetanothermagiclamp_autogen/EWIEGA46WW/../../../../src/YetAnotherMagicLampEffect.h:25:10: fatal error: kwindeformeffect.h: Nie ma takiego pliku ani katalogu
   25 | #include <kwindeformeffect.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:85: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp.o] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:360: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/all] Błąd 2
make: *** [Makefile:146: all] Błąd 2
```

**Comment by shaooping** [comment]
All the same problem...

**Comment by angrylinuxuser** [comment]
Don't pull master branch pull Plasma/5.22.  master is working with development 5.23 branch

**Comment by zzag** [comment]
That's right. master builds only with master branch. I added the checkout step in README.

**Comment by WeiFengWa** [comment]
Have you solved this problem? I have the same problem

**Comment by wojtekKrol** [comment]
I did many years ago, but I'm not using Linux currently therefore I'm unable to help you.

**Comment by shaooping** [comment]
> Have you solved this problem? I have the same problem

应该是个国人，因为环境安装了anaconda，所以安装kwin-effects-yet-another-magic-lamp的时候，将~/.zshrc或者一般是~/.bashrc里的anaconda环境先注释掉，再进行安装，安装完以后可以去掉注释，之前有好几个插件都是因为这个环境而无法生效，全部按照前面这个方法解决的。
